
LUANATIVEDIR 		= $(CLSDIR)/luanative

LOCAL_LDLIBS		+= -landroid

LOCAL_C_INCLUDES	+= $(LOCAL_PATH)/$(LUANATIVEDIR)

LUANATIVESRC 		:= $(LUANATIVEDIR)/com_lua_LuaNative.c
LUANATIVESRC	 	+= $(LUANATIVEDIR)/lua_print.c
LUANATIVESRC	 	+= $(LUANATIVEDIR)/lua_file_io.c
LUANATIVESRC	 	+= $(LUANATIVEDIR)/lua_loader.c
LUANATIVESRC	 	+= $(LUANATIVEDIR)/lua_main.c
LUANATIVESRC	 	+= $(LUANATIVEDIR)/lua_to_java.c

LOCAL_SRC_FILES += $(LUANATIVESRC)
